name: or-tool build

on: push
    
    
jobs:
  or-tool:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout or-tool 
      - uses: actions/checkout@v3
        with:
         repository: google/or-tools/blob/stable/
         ref: stable
         path: '../ortools'

      - name: Install Ninja
        uses: llvm/actions/install-ninja@main


